go.property("light", vmath.vector4(0, -3, 3, 0))

function init(self)
    msg.post(".", "acquire_input_focus")
    msg.post("@render:", "use_camera_projection")
    msg.post("camera", "acquire_camera_focus")
end

function on_input(self, action_id, action)
    if action_id == hash("touch") then
        local rot = go.get(".", "euler")
        rot.y = rot.y + action.dx
        go.set(".", "euler", rot)
    end
end

function on_reload(self)
    self.light = vmath.vector4(20, 10,  10, 0)
end
